name: Publish to Netlify
on:
  push:
    branches:
      - "main"

  workflow_dispatch:
env:
    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check dir
        run: ls -lah
      - name: Install dependency
        run: npm install
      - name: Build app
        run: npm run build
      - name: Netlify Actions
        # You may pin to the exact commit or the version.
        # uses: nwtgck/actions-netlify@5da65c9f74c7961c5501a3ba329b8d0912f39c03
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          # Publish directory
          publish-dir: dist
